name: Cresco Media Monitor


on:

  workflow_dispatch:

  schedule:

    # každý den v 7:00 UTC
    # (v ČR v zimě 8:00, v létě 9:00)
    - cron: "0 7 * * *"



jobs:


  monitor:


    runs-on: ubuntu-latest


    steps:


      - name: Stažení projektu
        uses: actions/checkout@v4



      - name: Nastavení Pythonu
        uses: actions/setup-python@v5

        with:

          python-version: "3.12"



      - name: Instalace knihoven
        run: |

          pip install -r requirements.txt



      - name: Spuštění monitoringu
        run: |

          python main.py


        env:


          EMAIL_USER:
            ${{ secrets.EMAIL_USER }}


          EMAIL_PASSWORD:
            ${{ secrets.EMAIL_PASSWORD }}
